storage:
  path: ./storage

pairs:
  - name: default
    migration_table: migration_status
    staging:
      provider: postgres
      dsn: postgres://user_a:password_a@localhost:50101/service_stg?sslmode=disable
      schema: public
    production:
      provider: postgres
      dsn: postgres://user_b:password_b@localhost:50102/service_prod?sslmode=disable
      schema: public
