version: "3.9"

services:
  service_stg_db:
    image: postgres:15-alpine
    container_name: service_stg_db
    environment:
      POSTGRES_USER: user_a
      POSTGRES_PASSWORD: password_a
      POSTGRES_DB: service_stg
    ports:
      - "50101:5432"
    volumes:
      - service_stg_data:/var/lib/postgresql/data

  service_prod_db:
    image: postgres:15-alpine
    container_name: service_prod_db
    environment:
      POSTGRES_USER: user_b
      POSTGRES_PASSWORD: password_b
      POSTGRES_DB: service_prod
    ports:
      - "50102:5432"
    volumes:
      - service_prod_data:/var/lib/postgresql/data

volumes:
  service_stg_data:
  service_prod_data:
